"""
Tests for V1.8.4 branding, watermark, and export filename validation.
"""
import sys
import os
import importlib
import re

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WINDOWS_ILLEGAL = r'[\\/:*?"<>|]'
EMOJI_PATTERN = re.compile(
    r'[\U0001F000-\U0001FFFF\U00002600-\U000027FF\U00002B00-\U00002BFF]'
)


# ══════════════════════════════════════════════════════════════════════════════
# A. Config branding defaults
# ══════════════════════════════════════════════════════════════════════════════

class TestBrandingConfig:
    def test_brand_name_default(self, monkeypatch):
        monkeypatch.delenv("ASTRO_BRAND_NAME", raising=False)
        import config
        importlib.reload(config)
        assert config.BRAND_NAME == "Astro Destiny Analyzer"

    def test_brand_tagline_default(self, monkeypatch):
        monkeypatch.delenv("ASTRO_BRAND_TAGLINE", raising=False)
        import config
        importlib.reload(config)
        assert config.BRAND_TAGLINE != ""

    def test_report_watermark_not_empty(self, monkeypatch):
        monkeypatch.delenv("ASTRO_REPORT_WATERMARK", raising=False)
        import config
        importlib.reload(config)
        assert config.REPORT_WATERMARK != ""

    def test_brand_name_env_override(self, monkeypatch):
        monkeypatch.setenv("ASTRO_BRAND_NAME", "MyBrand")
        import config
        importlib.reload(config)
        assert config.BRAND_NAME == "MyBrand"


# ══════════════════════════════════════════════════════════════════════════════
# B. Markdown export — brand footer
# ══════════════════════════════════════════════════════════════════════════════

class TestMarkdownExport:
    def _make_report(self):
        from datetime import date, time
        from core.models import BirthProfile, AnalysisTheme, ReportLanguage, ReportLength
        from reports.generator import ReportGenerator
        p = BirthProfile(
            name="TestUser",
            birth_date=date(1990, 1, 1),
            birth_time=time(12, 0),
            birth_city="台北",
            birth_country="台灣",
            themes=list(AnalysisTheme),
            report_language=ReportLanguage.TRADITIONAL_CHINESE,
            report_length=ReportLength.SHORT,
            birth_latitude=25.0330,
            birth_longitude=121.5654,
            birth_timezone_offset=8.0,
            birth_time_is_known=True,
        )
        return ReportGenerator().generate(p)

    def test_markdown_contains_generated_by(self):
        from reports.markdown_exporter import MarkdownExporter
        report = self._make_report()
        md = MarkdownExporter().export(report)
        assert "Generated by" in md

    def test_markdown_contains_version(self):
        from reports.markdown_exporter import MarkdownExporter
        from config import APP_VERSION
        report = self._make_report()
        md = MarkdownExporter().export(report)
        assert APP_VERSION in md

    def test_markdown_no_debug_strings(self):
        from reports.markdown_exporter import MarkdownExporter
        report = self._make_report()
        md = MarkdownExporter().export(report).lower()
        assert "debug" not in md


# ══════════════════════════════════════════════════════════════════════════════
# C. HTML export — brand and version
# ══════════════════════════════════════════════════════════════════════════════

class TestHtmlExport:
    def _make_report(self):
        from datetime import date, time
        from core.models import BirthProfile, AnalysisTheme, ReportLanguage, ReportLength
        from reports.generator import ReportGenerator
        p = BirthProfile(
            name="TestUser",
            birth_date=date(1990, 1, 1),
            birth_time=time(12, 0),
            birth_city="台北",
            birth_country="台灣",
            themes=list(AnalysisTheme),
            report_language=ReportLanguage.TRADITIONAL_CHINESE,
            report_length=ReportLength.SHORT,
            birth_latitude=25.0330,
            birth_longitude=121.5654,
            birth_timezone_offset=8.0,
            birth_time_is_known=True,
        )
        return ReportGenerator().generate(p)

    def test_html_contains_brand_name(self):
        from reports.html_exporter import HtmlExporter
        from config import BRAND_NAME
        report = self._make_report()
        html = HtmlExporter().export(report)
        assert BRAND_NAME in html

    def test_html_contains_app_version(self):
        from reports.html_exporter import HtmlExporter
        from config import APP_VERSION
        report = self._make_report()
        html = HtmlExporter().export(report)
        assert APP_VERSION in html

    def test_html_no_debug_strings(self):
        from reports.html_exporter import HtmlExporter
        report = self._make_report()
        html = HtmlExporter().export(report).lower()
        assert "debug" not in html

    def test_html_contains_watermark(self):
        from reports.html_exporter import HtmlExporter
        from config import REPORT_WATERMARK
        report = self._make_report()
        html = HtmlExporter().export(report)
        assert REPORT_WATERMARK in html


# ══════════════════════════════════════════════════════════════════════════════
# D. Word export — brand
# ══════════════════════════════════════════════════════════════════════════════

class TestWordExport:
    def test_docx_exporter_references_brand(self):
        src_path = os.path.join(PROJECT_ROOT, "reports", "docx_exporter.py")
        with open(src_path, encoding="utf-8") as f:
            src = f.read()
        assert "BRAND_NAME" in src
        assert "REPORT_WATERMARK" in src


# ══════════════════════════════════════════════════════════════════════════════
# E. Compat export filename
# ══════════════════════════════════════════════════════════════════════════════

class TestCompatFilename:
    def test_filename_contains_relationship_report(self):
        from compatibility.exporters import make_compat_filename
        fname = make_compat_filename("A方", "B方", "html")
        assert "relationship_report" in fname

    def test_filename_no_illegal_chars(self):
        from compatibility.exporters import make_compat_filename
        fname = make_compat_filename("A 方", "B 方", "html")
        assert not re.search(WINDOWS_ILLEGAL, fname)

    def test_filename_no_emoji(self):
        from compatibility.exporters import make_compat_filename
        fname = make_compat_filename("💑 情侶A", "💑 情侶B", "html")
        assert not EMOJI_PATTERN.search(fname)

    def test_filename_chinese_safe(self):
        from compatibility.exporters import make_compat_filename
        fname = make_compat_filename("張三", "李四", "html")
        assert "relationship_report" in fname
        assert not re.search(WINDOWS_ILLEGAL, fname)

    def test_filename_spaces_to_underscore(self):
        from compatibility.exporters import make_compat_filename
        fname = make_compat_filename("Name A", "Name B", "html")
        assert " " not in fname

    def test_filename_correct_extension(self):
        from compatibility.exporters import make_compat_filename
        assert make_compat_filename("A", "B", "html").endswith(".html")
        assert make_compat_filename("A", "B", "docx").endswith(".docx")


# ══════════════════════════════════════════════════════════════════════════════
# F. Report content — no internal strings
# ══════════════════════════════════════════════════════════════════════════════

class TestReportContent:
    def _make_report(self):
        from datetime import date, time
        from core.models import BirthProfile, AnalysisTheme, ReportLanguage, ReportLength
        from reports.generator import ReportGenerator
        p = BirthProfile(
            name="CustomerName",
            birth_date=date(1990, 1, 1),
            birth_time=time(12, 0),
            birth_city="台北",
            birth_country="台灣",
            themes=list(AnalysisTheme),
            report_language=ReportLanguage.TRADITIONAL_CHINESE,
            report_length=ReportLength.SHORT,
            birth_latitude=25.0330,
            birth_longitude=121.5654,
            birth_timezone_offset=8.0,
            birth_time_is_known=True,
        )
        return ReportGenerator().generate(p)

    def test_report_no_golden_case(self):
        from reports.markdown_exporter import MarkdownExporter
        report = self._make_report()
        md = MarkdownExporter().export(report)
        assert "golden case" not in md.lower()

    def test_html_no_ziwei_calibration_tool(self):
        from reports.html_exporter import HtmlExporter
        report = self._make_report()
        html = HtmlExporter().export(report)
        # "紫微校準" is the calibration tool page — should not appear in customer reports
        assert "紫微校準" not in html
