"""
V1.9.6 Lead Magnet — Rendering Templates.
"""
from __future__ import annotations
from lead_magnet.models import FreeReportResult

_FOOTER = "Generated by Astro Destiny Analyzer · 整合命盤分析系統"

_CAPTURE_COPY = {
    "zodiac_free_summary": {
        "title": "取得免費星座速覽",
        "description": "輸入你的出生日期，立即取得個人化太陽星座速覽摘要。",
        "form_hint": "請填寫姓名、Email 與出生日期，以產生免費星座速覽。",
        "consent_text": "我同意將以上資料儲存在本機，用於產生免費摘要與後續聯繫測試。此版本不會將資料送往外部服務。",
        "button_label": "取得免費星座速覽",
    },
    "human_design_free_summary": {
        "title": "取得免費人類圖 Type 速覽",
        "description": "輸入出生日期與時間，取得人類圖 Type 與 Authority 速覽。",
        "form_hint": "人類圖需要精確出生時間與出生地，以計算正確的 Type。",
        "consent_text": "我同意將以上資料儲存在本機，用於產生免費摘要與後續聯繫測試。此版本不會將資料送往外部服務。",
        "button_label": "取得免費人類圖速覽",
    },
    "compatibility_free_summary": {
        "title": "取得免費合盤初評",
        "description": "輸入雙方的出生資料，取得初步關係探索摘要。",
        "form_hint": "請填寫雙方的姓名、Email 與出生日期，以產生合盤初步探索。",
        "consent_text": "我同意將以上資料儲存在本機，用於產生免費摘要與後續聯繫測試。此版本不會將資料送往外部服務。",
        "button_label": "取得免費合盤初評",
    },
    "integrated_free_summary": {
        "title": "取得免費整合命盤摘要",
        "description": "了解西洋占星、八字、紫微與人類圖如何互補，取得整合命盤初步摘要。",
        "form_hint": "請填寫姓名、Email 與出生日期，以產生整合命盤摘要。",
        "consent_text": "我同意將以上資料儲存在本機，用於產生免費摘要與後續聯繫測試。此版本不會將資料送往外部服務。",
        "button_label": "取得免費整合摘要",
    },
}

_UPGRADE_CTA = {
    "zodiac_free_summary": {
        "title": "建立完整命盤報告",
        "description": "完整西洋占星命盤包含太陽、月亮、上升、行星、宮位與相位解讀。",
        "button_label": "建立完整命盤報告",
        "target": "📝 輸入資料",
    },
    "human_design_free_summary": {
        "title": "建立完整人類圖報告",
        "description": "完整人類圖報告包含 Type、Authority、Profile 與所有中心、閘門通道解讀。",
        "button_label": "建立完整人類圖報告",
        "target": "📝 輸入資料",
    },
    "compatibility_free_summary": {
        "title": "建立完整合盤報告",
        "description": "完整合盤報告包含 Synastry 相位分析、Composite 合盤與多維度相容性評分。",
        "button_label": "建立完整合盤報告",
        "target": "💕 合盤分析",
    },
    "integrated_free_summary": {
        "title": "建立完整整合命盤報告",
        "description": "完整整合命盤報告包含西洋占星、八字、紫微斗數與人類圖的多系統解讀。",
        "button_label": "建立完整整合命盤報告",
        "target": "📝 輸入資料",
    },
}


def render_free_report_markdown(result: FreeReportResult) -> str:
    """Render FreeReportResult as Markdown string."""
    parts = []
    parts.append(f"# {result.title}")
    parts.append("")
    if result.summary:
        parts.append(result.summary)
        parts.append("")
    for section in result.sections:
        if section.heading:
            parts.append(f"## {section.heading}")
        if section.body:
            parts.append(section.body)
            parts.append("")
        if section.bullets:
            for b in section.bullets:
                parts.append(f"- {b}")
            parts.append("")
    if result.cta_title or result.cta_button_label:
        parts.append("---")
        parts.append("")
        if result.cta_title:
            parts.append(f"### {result.cta_title}")
        if result.cta_description:
            parts.append(result.cta_description)
            parts.append("")
        if result.cta_button_label:
            parts.append(f"**→ {result.cta_button_label}**")
            parts.append("")
    if result.disclaimer:
        parts.append(f"> {result.disclaimer}")
        parts.append("")
    parts.append(f"---\n*{_FOOTER}*")
    return "\n".join(parts)


def render_free_report_html(result: FreeReportResult) -> str:
    """Render FreeReportResult as a self-contained HTML page. No JS/CDN."""
    def _esc(t: str) -> str:
        return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")

    body_parts = []
    body_parts.append(f'<h1>{_esc(result.title)}</h1>')
    if result.summary:
        body_parts.append(f'<p class="summary">{_esc(result.summary)}</p>')
    for section in result.sections:
        body_parts.append('<div class="section">')
        if section.heading:
            body_parts.append(f'  <h2>{_esc(section.heading)}</h2>')
        if section.body:
            body_parts.append(f'  <p>{_esc(section.body)}</p>')
        if section.bullets:
            body_parts.append('  <ul>')
            for b in section.bullets:
                body_parts.append(f'    <li>{_esc(b)}</li>')
            body_parts.append('  </ul>')
        body_parts.append('</div>')
    if result.cta_title or result.cta_button_label:
        body_parts.append('<div class="cta-block">')
        if result.cta_title:
            body_parts.append(f'  <h3>{_esc(result.cta_title)}</h3>')
        if result.cta_description:
            body_parts.append(f'  <p>{_esc(result.cta_description)}</p>')
        if result.cta_button_label:
            body_parts.append(f'  <p class="cta-btn">{_esc(result.cta_button_label)}</p>')
        body_parts.append('</div>')
    if result.disclaimer:
        body_parts.append(f'<p class="disclaimer">{_esc(result.disclaimer)}</p>')
    body_html = "\n".join(body_parts)

    return f"""<!DOCTYPE html>
<html lang="zh-Hant">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(result.title)}</title>
<style>
body{{font-family:sans-serif;max-width:800px;margin:2rem auto;padding:0 1rem;color:#222;line-height:1.7}}
h1{{font-size:1.8rem;margin-bottom:.5rem}}
h2{{font-size:1.3rem;margin-top:1.5rem}}
h3{{font-size:1.1rem}}
.summary{{font-size:1.05rem;background:#f8f8f8;padding:1rem;border-left:4px solid #ccc}}
.section{{margin:1.5rem 0}}
.cta-block{{background:#f0f4ff;border:1px solid #c0c8e8;border-radius:6px;padding:1rem 1.5rem;margin:2rem 0}}
.cta-btn{{font-weight:bold;color:#1a3a8f}}
.disclaimer{{font-size:.85rem;color:#888;margin-top:2rem;border-top:1px solid #eee;padding-top:.75rem}}
footer{{margin-top:3rem;padding-top:1rem;border-top:1px solid #ddd;color:#999;font-size:.8rem;text-align:center}}
</style>
</head>
<body>
{body_html}
<footer>{_esc(_FOOTER)}</footer>
</body>
</html>"""


def render_lead_capture_copy(report_type: str) -> dict:
    """Return UI copy dict for the lead capture form."""
    return dict(_CAPTURE_COPY.get(report_type, _CAPTURE_COPY["integrated_free_summary"]))


def render_upgrade_cta(report_type: str) -> dict:
    """Return upgrade CTA dict for the given report type."""
    return dict(_UPGRADE_CTA.get(report_type, _UPGRADE_CTA["integrated_free_summary"]))
